/**
 * Neighborhood (label) page SSR generator.
 *
 * Handles /:citySlug/:labelSlug URLs where the second segment is a
 * slugified label text (e.g. /bangalore/cubbon-park-morning-jogs-peaceful).
 * These links are generated by city pages: <a href="/{city}/{area.slug}">
 * but previously had no server-side handler, causing 404s.
 */

import { db, labelsTable } from "@workspace/db";
import { sql } from "drizzle-orm";
import { ssrHtmlShell } from "./ssrShared";
import { CITIES } from "./citySSR";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/[\s]+/g, "-")
    .replace(/-+/g, "-");
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
}

function costLabel(cost: string): string {
  switch (cost) {
    case "$":    return "Budget-friendly";
    case "$$":   return "Moderate";
    case "$$$":  return "Expensive";
    case "$$$$": return "Luxury";
    default:     return cost;
  }
}

function safetyLabel(safety: number): string {
  if (safety >= 4.5) return "Very safe";
  if (safety >= 3.5) return "Safe";
  if (safety >= 2.5) return "Moderate";
  if (safety >= 1.5) return "Use caution";
  return "High risk";
}

export async function getNeighborhoodHtml(
  citySlug: string,
  labelSlug: string
): Promise<string | null> {
  const city = CITIES.find((c) => c.slug === citySlug);
  if (!city) return null;

  const labels = await db
    .select()
    .from(labelsTable)
    .where(
      sql`lat >= ${city.latMin} AND lat <= ${city.latMax} AND lng >= ${city.lngMin} AND lng <= ${city.lngMax}`
    );

  const matching = labels
    .filter((l) => slugify(l.text) === labelSlug)
    .sort((a, b) => (b.upvotes - b.downvotes) - (a.upvotes - a.downvotes));

  if (matching.length === 0) return null;

  const label = matching[0];
  const score  = (label.upvotes ?? 0) - (label.downvotes ?? 0);
  const vibes  = Array.isArray(label.vibe) ? (label.vibe as string[]) : [];

  const bodyHtml = `
    <div class="mb-2">
      <nav class="text-sm text-gray-400 mb-4">
        <a href="/" class="hover:text-teal-600">PlaceLabels</a>
        <span class="mx-2">/</span>
        <a href="/${city.slug}" class="hover:text-teal-600">${escapeHtml(city.name)}</a>
        <span class="mx-2">/</span>
        <span class="text-gray-700">${escapeHtml(label.text)}</span>
      </nav>

      <h1 class="text-3xl sm:text-4xl font-bold text-gray-900 mb-2">${escapeHtml(label.text)}</h1>
      <p class="text-gray-500 text-base mb-6">Neighborhood in ${escapeHtml(city.name)} — crowd-sourced community insight</p>

      <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">
        <div class="rounded-xl p-4 text-center bg-blue-50 border border-blue-100">
          <p class="text-2xl font-bold text-blue-700">${label.safety}/5</p>
          <p class="text-xs text-blue-600 mt-1 font-medium">Safety</p>
          <p class="text-xs text-gray-400 mt-0.5">${escapeHtml(safetyLabel(label.safety))}</p>
        </div>
        <div class="rounded-xl p-4 text-center bg-green-50 border border-green-100">
          <p class="text-2xl font-bold text-green-700">${escapeHtml(label.cost)}</p>
          <p class="text-xs text-green-600 mt-1 font-medium">Cost</p>
          <p class="text-xs text-gray-400 mt-0.5">${escapeHtml(costLabel(label.cost))}</p>
        </div>
        <div class="rounded-xl p-4 text-center ${score >= 0 ? "bg-teal-50 border-teal-100" : "bg-red-50 border-red-100"} border">
          <p class="text-2xl font-bold ${score >= 0 ? "text-teal-700" : "text-red-700"}">${score > 0 ? "+" : ""}${score}</p>
          <p class="text-xs ${score >= 0 ? "text-teal-600" : "text-red-600"} mt-1 font-medium">Community Score</p>
          <p class="text-xs text-gray-400 mt-0.5">${label.upvotes ?? 0} up · ${label.downvotes ?? 0} down</p>
        </div>
        ${vibes.length > 0 ? `
        <div class="rounded-xl p-4 text-center bg-purple-50 border border-purple-100">
          <p class="text-xl font-bold text-purple-700 truncate">${escapeHtml(vibes[0])}</p>
          <p class="text-xs text-purple-600 mt-1 font-medium">Vibe</p>
          <p class="text-xs text-gray-400 mt-0.5 truncate">${vibes.slice(1).map((v) => escapeHtml(v)).join(" · ") || "Local feel"}</p>
        </div>` : `
        <div class="rounded-xl p-4 text-center bg-gray-50 border border-gray-100">
          <p class="text-xl font-bold text-gray-500">—</p>
          <p class="text-xs text-gray-500 mt-1 font-medium">Category</p>
          <p class="text-xs text-gray-400 mt-0.5">${escapeHtml(label.category ?? "General")}</p>
        </div>`}
      </div>

      ${vibes.length > 0 ? `
      <div class="bg-white rounded-xl border border-gray-200 p-5 mb-6">
        <h2 class="font-semibold text-gray-900 mb-3">Local Vibes</h2>
        <div class="flex flex-wrap gap-2">
          ${vibes.map((v) => `<span class="px-3 py-1 bg-teal-50 text-teal-700 text-sm font-medium rounded-full border border-teal-100">${escapeHtml(v)}</span>`).join("")}
        </div>
      </div>` : ""}

      <div class="bg-white rounded-xl border border-gray-200 p-5 mb-6">
        <h2 class="font-semibold text-gray-900 mb-3">About ${escapeHtml(label.text)}</h2>
        <p class="text-gray-600 leading-relaxed">
          ${escapeHtml(label.text)} is a crowd-sourced neighborhood label in ${escapeHtml(city.name)}
          with a safety rating of <strong>${label.safety}/5</strong> (${escapeHtml(safetyLabel(label.safety).toLowerCase())})
          and a cost tier of <strong>${escapeHtml(label.cost)}</strong> (${escapeHtml(costLabel(label.cost).toLowerCase())}).
          ${label.upvotes ?? 0} community members have upvoted this area${label.downvotes && label.downvotes > 0 ? `, while ${label.downvotes} have downvoted it` : ""}.
          ${vibes.length > 0 ? ` The neighborhood is described as ${vibes.map((v) => `<strong>${escapeHtml(v)}</strong>`).join(", ")}.` : ""}
        </p>
      </div>

      <div class="bg-gradient-to-r from-teal-50 to-blue-50 rounded-xl border border-teal-100 p-5 mb-8">
        <h2 class="font-semibold text-gray-900 mb-2">🗺️ Explore on the interactive map</h2>
        <p class="text-sm text-gray-600 mb-3">See this neighborhood live with real-time cost estimates, transit times between areas, and all community labels around it.</p>
        <a href="/" class="inline-flex items-center gap-2 bg-teal-600 text-white text-sm font-semibold px-4 py-2 rounded-lg hover:bg-teal-700 transition-colors">Open interactive map →</a>
      </div>
    </div>

    <section class="mb-10">
      <h2 class="text-lg font-bold text-gray-900 mb-4">Explore ${escapeHtml(city.name)} Neighborhoods</h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        ${[
          { slug: "safe-neighborhoods",   emoji: "🛡️", label: "Safe Neighborhoods" },
          { slug: "affordable-areas",      emoji: "💰", label: "Affordable Areas" },
          { slug: "family-friendly",       emoji: "👨‍👩‍👧‍👦", label: "Family-Friendly" },
          { slug: "transit-friendly",      emoji: "🚇", label: "Transit-Friendly" },
          { slug: "nightlife-areas",       emoji: "🎉", label: "Best Nightlife" },
          { slug: "expat-neighborhoods",   emoji: "🌍", label: "Expat-Friendly" },
        ]
          .map(
            ({ slug, emoji, label: catLabel }) => `
          <a href="/${city.slug}/${slug}" class="flex items-center gap-3 bg-white border border-gray-200 rounded-xl p-3 hover:border-teal-300 hover:shadow-sm transition-all">
            <span class="text-xl">${emoji}</span>
            <span class="text-sm font-medium text-gray-800">${catLabel} in ${escapeHtml(city.name)}</span>
          </a>`
          )
          .join("")}
      </div>
    </section>

    <section>
      <h2 class="text-lg font-bold text-gray-900 mb-4">More cities on PlaceLabels</h2>
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-3">
        ${CITIES.filter((c) => c.slug !== city.slug)
          .slice(0, 8)
          .map(
            (c) => `<a href="/${c.slug}" class="bg-white border border-gray-200 rounded-lg p-3 text-center hover:border-teal-300 hover:shadow-sm transition-all">
            <p class="font-semibold text-gray-900 text-sm">${escapeHtml(c.name)}</p>
            <p class="text-xs text-gray-400 mt-0.5">Browse neighborhoods</p>
          </a>`
          )
          .join("")}
      </div>
    </section>
  `;

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "PlaceLabels",        item: "https://placelabels.com" },
      { "@type": "ListItem", position: 2, name: city.name,            item: `https://placelabels.com/${city.slug}` },
      { "@type": "ListItem", position: 3, name: label.text,           item: `https://placelabels.com/${city.slug}/${labelSlug}` },
    ],
  };

  const placeSchema = {
    "@context": "https://schema.org",
    "@type": "Place",
    name: label.text,
    description: `${label.text} is a neighborhood in ${city.name}. Safety: ${label.safety}/5. Cost: ${label.cost}${vibes.length > 0 ? `. Vibe: ${vibes.join(", ")}` : ""}.`,
    geo: {
      "@type": "GeoCoordinates",
      latitude: label.lat,
      longitude: label.lng,
    },
    containedInPlace: {
      "@type": "City",
      name: city.name,
    },
  };

  return ssrHtmlShell({
    title: `${label.text} — ${city.name} Neighborhood | PlaceLabels`,
    description: `${label.text} in ${city.name}: safety ${label.safety}/5 (${safetyLabel(label.safety).toLowerCase()}), cost ${label.cost} (${costLabel(label.cost).toLowerCase()}).${vibes.length > 0 ? ` Known for: ${vibes.slice(0, 3).join(", ")}.` : ""} Community-reviewed neighborhood data.`,
    canonical: `https://placelabels.com/${city.slug}/${labelSlug}`,
    bodyHtml,
    schemaJson: breadcrumbSchema,
    schemaJsons: [placeSchema],
  });
}
